FROM 839431922263.dkr.ecr.us-east-2.amazonaws.com/dockerproductionaws/microtrader-base
MAINTAINER Akash nigam <Akashnigam802@gmail.com>
LABEL application.component=microtrader-portfolio

# Copy application artefacts
ARG app_version
LABEL application.version=${app_version}
COPY build/jars/microtrader-portfolio-${app_version}-fat.jar /app/app.jar
