FROM 839431922263.dkr.ecr.ap-south-1.amazonaws.com/dockerproductionaws/microtrader-base
MAINTAINER Akash Nigam <Akashnigam802@gmail.com>
LABEL application.component=microtrader-quote
HEALTHCHECK --interval=3s --retries=20 CMD curl -fs http://localhost:${HTTP_PORT:-35000}/${HTTP_ROOT}

# Copy application artefacts
ARG app_version
LABEL application.version=${app_version}
COPY build/jars/microtrader-quote-${app_version}-fat.jar /app/app.jar
